#!/usr/bin/env node
// Wraps colour literals in the client stylesheets with
// light-dark(<original>, var(--dk-*)) so light mode stays byte-identical and
// dark mode reads from a small token palette. Re-run after merging upstream.
//
//   node scripts/theme/tokenize-css.mjs            dry run: report changes
//   node scripts/theme/tokenize-css.mjs --write    apply changes
//   node scripts/theme/tokenize-css.mjs --check    exit 1 if bare literals remain
//
// The trailing token block in each stylesheet is regenerated from
// tokens.<name>.css on --write, between the BLOCK_START/BLOCK_END markers.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const BLOCK_START = '/* @theme-tokens:start (generated by scripts/theme) */';
const BLOCK_END = '/* @theme-tokens:end */';

const TARGETS = [
  { file: 'src/client/style.css', tokens: 'tokens.style.css', palette: 'app' },
  {
    file: 'src/client/editor.css',
    tokens: 'tokens.editor.css',
    palette: 'doc',
  },
];

// Declarations that are left alone: custom properties, shadows (low-alpha dark
// shadows read fine on charcoal), and the voice call surface, which is dark
// teal with white text in both themes.
const SKIP_PROPERTY = /^(--|box-shadow$|text-shadow$|filter$|backdrop-filter$)/;
const SKIP_SELECTOR = /\.call-/;

// Hand-picked dark tokens for literals the classifier cannot judge, keyed by
// "<file>:<literal or keyword>:<role>" or "<literal>:<role>" for both files.
const OVERRIDES = {
  '#2f34464d:surface': 'scrim',
  '#34394d30:surface': 'scrim',
  '#ffffff88:surface': 'overlay-light',
  '#aec1a433:surface': 'doc-selection',
};

// White text depends on the fill behind it: coloured fills stay dark in dark
// mode (keep white text), neutral near-black fills invert to a light pill.
const TEXT_ON_FILL = {
  '.send-button': 'on-fill',
  '.primary': 'on-fill',
  '.chat-bubble.user': 'on-fill',
  '.chat-bubble.user a': 'on-fill',
  '.page-review-card footer .review-primary': 'on-fill',
  '.template-app .send-button': 'accent-ink',
  '.computer-control-pill button': 'accent-ink',
  '.document-primary': 'doc-accent-ink',
  '.document-primary:hover:not(:disabled)': 'doc-accent-ink',
  '.document-chat-dock-bottom > button': 'doc-accent-ink',
};

// Surfaces whose role the classifier cannot see: screenshot letterboxes (the
// images are never inverted) and floating panels that need elevation.
const SURFACE_BY_SELECTOR = {
  '.modal': 'raised',
  '.slash-menu': 'doc-raised',
  '.document-dropdown': 'doc-raised',
  '.computer-panel .computer-screen': 'screen-frame',
  '.inline-computer-preview img': 'screen-frame',
};

const args = new Set(process.argv.slice(2));
const write = args.has('--write');
const check = args.has('--check');

function rgb(hex) {
  let x = hex.slice(1).toLowerCase();
  if (x.length <= 4) x = [...x].map((c) => c + c).join('');
  const n = parseInt(x.slice(0, 6), 16);
  return {
    hex: `#${x}`,
    r: n >> 16,
    g: (n >> 8) & 255,
    b: n & 255,
    alpha: x.length === 8 ? parseInt(x.slice(6), 16) / 255 : 1,
  };
}

function describe({ r, g, b }) {
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const spread = max - min;
  const lum = Math.round(0.2126 * r + 0.7152 * g + 0.0722 * b);
  let hue = 0;
  if (spread) {
    if (max === r) hue = ((g - b) / spread) % 6;
    else if (max === g) hue = (b - r) / spread + 2;
    else hue = (r - g) / spread + 4;
    hue = (hue * 60 + 360) % 360;
  }
  return { spread, lum, hue };
}

function family(hue) {
  if (hue >= 190 && hue < 300) return 'info';
  if (hue >= 150 && hue < 190) return 'brand';
  if (hue >= 75 && hue < 150) return 'success';
  if (hue >= 25 && hue < 75) return 'warning';
  return 'danger';
}

function isNeutral(color, palette) {
  const { spread, lum, hue } = describe(color);
  const blueish = hue >= 190 && hue < 300;
  const sage = hue >= 60 && hue < 190;
  if (palette === 'doc' && sage) return spread <= 30;
  if (lum >= 215) return spread < (blueish ? 14 : 10);
  if (blueish) return spread <= 40;
  return spread <= 20;
}

function neutralToken(lum, role) {
  if (role === 'text') {
    if (lum <= 45) return 'ink-strong';
    if (lum <= 84) return 'ink';
    if (lum <= 125) return 'muted';
    if (lum <= 160) return 'muted-light';
    if (lum <= 215) return 'muted-faint';
    return null; // light text sits on a dark fill; pick by hand
  }
  if (role === 'surface') {
    if (lum >= 252) return 'page';
    if (lum >= 247) return 'surface-2';
    if (lum >= 242) return 'surface-3';
    if (lum >= 236) return 'chip';
    if (lum >= 226) return 'chip-strong';
    if (lum >= 200) return 'line-strong';
    if (lum > 60) return 'line-bold';
    return 'accent';
  }
  if (lum >= 236) return 'line';
  if (lum >= 200) return 'line-strong';
  if (lum >= 120) return 'line-bold';
  if (lum > 60) return 'muted';
  return 'accent';
}

function coloredToken(color, role, palette) {
  const { lum, hue } = describe(color);
  let fam = family(hue);
  if (palette === 'doc' && (fam === 'brand' || fam === 'success'))
    fam = 'doc-link';
  if (role === 'text') return fam;
  if (role === 'surface') {
    if (lum >= 215) return `${fam}-soft`;
    if (lum < 175) return `${fam}-fill`;
    return fam;
  }
  return lum >= 200 ? `${fam}-line` : fam;
}

function roleOf(property) {
  if (/^(color|caret-color|accent-color|fill|stroke)$/.test(property))
    return 'text';
  if (/^background/.test(property)) return 'surface';
  return 'border';
}

function tokenFor(literal, role, palette, file, selector) {
  const key = literal.toLowerCase();
  const bare = selector.replace(/\s*\{$/, '');
  const isWhite = /^(white|#fff|#ffffff)$/.test(key);
  if (isWhite && role === 'text' && TEXT_ON_FILL[bare])
    return TEXT_ON_FILL[bare];
  if (role === 'surface' && SURFACE_BY_SELECTOR[bare])
    return SURFACE_BY_SELECTOR[bare];
  const color = key === 'white' ? rgb('#fff') : rgb(key);
  const id = key === 'white' ? 'white' : color.hex;
  const override =
    OVERRIDES[`${file}:${id}:${role}`] ?? OVERRIDES[`${id}:${role}`];
  if (override) return override;
  if (color.alpha < 1) return null;
  const neutral = isNeutral(color, palette);
  const token = neutral
    ? neutralToken(describe(color).lum, role)
    : coloredToken(color, role, palette);
  if (!token) return null;
  // Editor neutrals have their own sage-tinted dark palette.
  return palette === 'doc' && neutral ? `doc-${token}` : token;
}

const VALUE =
  /light-dark\((?:[^()]|\([^()]*\))*\)|#[0-9a-f]{3,8}\b|\bwhite\b/gi;

function processFile(target) {
  const path = join(root, target.file);
  const source = readFileSync(path, 'utf8');
  const eol = source.includes('\r\n') ? '\r\n' : '\n';
  const body = source.split(BLOCK_START)[0].replace(/\s+$/, '');
  const lines = body.split(/\r?\n/);
  let selector = '';
  let pendingSelector = '';
  let property = '';
  const changes = [];
  const unmapped = [];
  const out = lines.map((line, index) => {
    const trimmed = line.trim();
    if (trimmed.endsWith('{')) {
      selector = `${pendingSelector} ${trimmed}`.trim();
      pendingSelector = '';
      property = '';
      return line;
    }
    // Selector lists span lines; declarations are formatted as "name: value".
    if (trimmed.endsWith(',') && !/^[a-z-]+\s*:\s/i.test(trimmed)) {
      pendingSelector += ` ${trimmed}`;
      return line;
    }
    if (trimmed.startsWith('}')) {
      property = '';
      return line;
    }
    if (trimmed.startsWith('/*') || !trimmed) return line;
    const declaration = line.match(/^(\s*)([a-z-]+)(\s*:\s*)(.*)$/i);
    let prefix = '';
    let value = line;
    if (declaration) {
      property = declaration[2].toLowerCase();
      prefix = declaration[1] + declaration[2] + declaration[3];
      value = declaration[4];
    }
    if (
      !property ||
      SKIP_PROPERTY.test(property) ||
      SKIP_SELECTOR.test(selector)
    )
      return line;
    const role = roleOf(property);
    const next = value.replace(VALUE, (match) => {
      if (match.toLowerCase().startsWith('light-dark')) return match;
      const token = tokenFor(
        match,
        role,
        target.palette,
        target.file,
        selector,
      );
      if (!token) {
        unmapped.push({ line: index + 1, selector, property, literal: match });
        return match;
      }
      changes.push({ line: index + 1, literal: match, token });
      return `light-dark(${match}, var(--dk-${token}))`;
    });
    return prefix + next;
  });
  const tokens = readFileSync(join(here, target.tokens), 'utf8')
    .replace(/\r\n/g, '\n')
    .trim();
  const result = [...out, '', BLOCK_START, tokens, BLOCK_END, '']
    .join('\n')
    .replace(/\n/g, eol);
  return { path, source, result, changes, unmapped };
}

let failed = false;
for (const target of TARGETS) {
  const { path, source, result, changes, unmapped } = processFile(target);
  const name = relative(root, path);
  const byToken = {};
  for (const change of changes)
    byToken[change.token] = (byToken[change.token] ?? 0) + 1;
  console.log(`\n${name}: ${changes.length} literals to wrap`);
  for (const [token, count] of Object.entries(byToken).sort())
    console.log(`  --dk-${token.padEnd(16)} ${count}`);
  if (unmapped.length) {
    console.log(`  unmapped (${unmapped.length}), resolve by hand:`);
    for (const item of unmapped)
      console.log(
        `    :${item.line} ${item.property}: ${item.literal}   ${item.selector.slice(0, 70)}`,
      );
  }
  if (check && (changes.length || unmapped.length || result !== source)) {
    failed = true;
    console.log('  check failed: stylesheet is not fully tokenized');
  }
  if (write && result !== source) {
    writeFileSync(path, result);
    console.log('  written');
  }
}
if (failed) process.exit(1);
